name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Download Terraform outputs
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: terraform-output
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}


      # -----------------------------
      # Get values
      # -----------------------------
      - name: Load Terraform outputs
        run: |
          DB_PORT=$(jq -r '.db_port.value' terraform-output/terraform-outputs.json)
          DB_HOST=$(jq -r '.db_host.value' terraform-output/terraform-outputs.json)
          BACKEND_PRIVATE_IP=$(jq -r '.backend_private_ip.value' terraform-output/terraform-outputs.json)
          BACKEND_PUBLIC_IP=$(jq -r '.backend_public_ip.value' terraform-output/terraform-outputs.json)
          FRONTEND_PUBLIC_IP=$(jq -r '.frontend_public_ip.value' terraform-output/terraform-outputs.json)

          echo "DB_PORT=$DB_PORT" >> "$GITHUB_ENV"
          echo "DB_HOST=$DB_HOST" >> "$GITHUB_ENV"
          echo "BACKEND_PRIVATE_IP=$BACKEND_PRIVATE_IP" >> "$GITHUB_ENV"
          echo "BACKEND_PUBLIC_IP=$BACKEND_PUBLIC_IP" >> "$GITHUB_ENV"
          echo "FRONTEND_PUBLIC_IP=$FRONTEND_PUBLIC_IP"


      - name: Deploy to EC2 backend
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ env.BACKEND_PUBLIC_IP}}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat > /opt/app/backend/.env <<EOF
            DB_HOST=${{ env.DB_HOST }}
            DB_PORT=${{env.DB_PORT}}
            DB_USER=${{ secrets.DB_USER }}
            DB_NAME=${{secrets.DB_NAME}}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            REPO_URL=${{secrets.REPO_URL}}
            EOF
            chmod 600 /opt/app/backend/.env
            cd /opt/app/backend
            ./deploy.sh

      - name: Deploy to EC2 frontend
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.FRONTEND_PUBLIC_IP}}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat > /opt/app/frontend/.env <<EOF
            BACKEND_PRIVATE_IP=${env.BACKEND_PRIVATE_IP}}
            FLASK_SECRET_KEY=${{secrets.FLASK_SECRET_KE}}
            REPO_URL=${{secrets.REPO_URL}}
            EOF
            chmod 600 /opt/app/frontend/.env
            cd /opt/app/frontend
            ./deploy.sh