name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest artifact from another workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: terraform.yml # The filename of your producer workflow
          name: terraform-outputs
          branch: main # Optional: only look for runs on this branch
      
     


      # -----------------------------
      # Get values
      # -----------------------------
      - name: Load Terraform outputs
        run: |
      
          DB_PORT=$(jq -r '.db_port.value' terraform-outputs.json)
          DB_HOST=$(jq -r '.db_host.value' terraform-outputs.json)
          BACKEND_PRIVATE_IP=$(jq -r '.backend_private_ip.value' terraform-outputs.json)
          BACKEND_PUBLIC_IP=$(jq -r '.backend_public_ip.value' terraform-outputs.json)
          FRONTEND_PUBLIC_IP=$(jq -r '.frontend_public_ip.value' terraform-outputs.json)    
          echo "DB_PORT=$DB_PORT" >> "$GITHUB_ENV"
          echo "DB_HOST=$DB_HOST" >> "$GITHUB_ENV"
          echo "BACKEND_PRIVATE_IP=$BACKEND_PRIVATE_IP" >> "$GITHUB_ENV"
          echo "BACKEND_PUBLIC_IP=$BACKEND_PUBLIC_IP" >> "$GITHUB_ENV"
          echo "FRONTEND_PUBLIC_IP=$FRONTEND_PUBLIC_IP" >> "$GITHUB_ENV"
      


      - name: Deploy to EC2 backend
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ env.BACKEND_PUBLIC_IP}}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /opt/app/backend/
            sudo touch /opt/app/backend/.env
            sudo tee /opt/app/backend/.env <<EOF
            DB_HOST=${{ env.DB_HOST }}
            DB_PORT=${{env.DB_PORT}}
            DB_USER=${{ secrets.DB_USER }}
            DB_NAME=${{secrets.DB_NAME}}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            REPO_URL=${{secrets.REPO_URL}}
            EOF
            
            sudo chmod 600 /opt/app/backend/.env
            sudo dnf update -y
            sudo dnf install -y python3 python3-pip git
            sudo git clone https://github.com/gautamindia/3tierappliction.git
            sudo cp -f /home/ec2-user/3tierappliction/app/backend/requirements.txt /opt/app/backend/requirements.txt
            sudo cp -f /home/ec2-user/3tierappliction/app/backend/app.py /opt/app/backend/app.py
            sudo rm -rf 3tierappliction
            cd /opt/app/backend
            set -a
            source .env
            set +a
          
            
            sudo python3 -m venv venv
            source venv/bin/activate
            sudo pip install -r requirements.txt
            nohup python3 app.py > /tmp/app.log 2>&1 & 
             

      - name: Deploy to EC2 frontend
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ env.FRONTEND_PUBLIC_IP}}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /opt/app/frontend/
            sudo touch /opt/app/frontend/.env
            sudo tee /opt/app/frontend/.env <<EOF
            BACKEND_PRIVATE_IP=${{env.BACKEND_PRIVATE_IP}}
            FLASK_SECRET_KEY=${{secrets.FLASK_SECRET_KEY}}
            REPO_URL=${{secrets.REPO_URL}}
            EOF
            
            sudo chmod 600 /opt/app/frontend/.env
            sudo dnf update -y
            sudo dnf install -y python3 python3-pip git
            sudo git clone https://github.com/gautamindia/3tierappliction.git
            sudo cp -f /home/ec2-user/3tierappliction/app/frontend/requirements.txt /opt/app/frontend/requirements.txt
            sudo cp -f /home/ec2-user/3tierappliction/app/frontend/app.py /opt/app/frontend/app.py
            sudo cp -f /home/ec2-user/3tierappliction/app/frontend/templates/index.html /opt/app/frontend/templates/index.html
            sudo rm -rf 3tierappliction
            cd /opt/app/frontend
            set -a
            source .env
            set +a
            sudo python3 -m venv venv
            source venv/bin/activate
            sudo pip install -r requirements.txt
            nohup python3 app.py > /tmp/app.log 2>&1 &
            