name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 backend
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.BACKEND_PUBLIC_IP}}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat > /opt/app/backend/.env <<EOF
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{secrets.DB_PORT}}
            DB_USER=${{ secrets.DB_USER }}
            DB_NAME=${{secrets.DB_NAME}}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            REPO_URL=${{secrets.REPO_URL}}
            EOF
            chmod 600 /opt/app/backend/.env
            cd /opt/app/backend
            ./deploy.sh

      - name: Deploy to EC2 frontend
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.FRONTEND_PUBLIC_IP}}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat > /opt/app/frontend/.env <<EOF
            BACKEND_PRIVATE_IP=${secrets.BACKEND_PRIVATE_IP}}
            FLASK_SECRET_KEY=${{secrets.FLASK_SECRET_KE}}
            REPO_URL=${{secrets.REPO_URL}}
            EOF
            chmod 600 /opt/app/frontend/.env
            cd /opt/app/frontend
            ./deploy.sh