name: Basic Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
  workflow_dispatch:

permissions:
  issues: write        # required so the manual-approval action can create/read the issue
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
      

      - name: Terraform init
        run: terraform init
        working-directory: ./terraform/environments/dev


      - name: Terraform validate
        run: terraform validate
        working-directory: ./terraform/environments/dev

      - name: Terraform plan
        run: terraform plan -var-file="terraform.tfvars.example" -out=tfplan
        working-directory: ./terraform/environments/dev

      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: gautamindia
          minimum-approvals: 1
          issue-title: "Approve Terraform Apply - Run #${{ github.run_number }}"
          issue-body: "Please review the Terraform plan in the workflow run and comment `approve` or `deny`.\n\nWorkflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Terraform apply
        run: terraform apply -var-file="terraform.tfvars.example" -auto-approve tfplan
        working-directory: ./terraform/environments/dev

      - name: Save Terraform outputs
        run: |
          terraform output -json > terraform-outputs.json

          echo "Terraform outputs:"
          cat terraform-outputs.json
        working-directory: ./terraform/environments/dev  


      # -----------------------------
      # Upload outputs as artifact
      # -----------------------------
      - name: Upload Terraform outputs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: terraform/terraform-outputs.json 